### ISSUE TITLE
Add context for new function example

### ISSUE THREAD

**Issue by rachel3834** [ShrRa/InterPython_Workshop_Example#15]
In the Setting the Scene section of the [Issue Diagnostics](https://shrra.github.io/python-intermediate-development/25-diagnosing-issues-improving-robustness/index.html) chapter, the instructions would benefit from clarifying whether the new function should be added to an existing file or as a new file and if so, in what part of the directory structure.

**Comment by RileyWClarke** [comment]
@rachel3834 The lesson materials are maintained on a separate repository here: https://github.com/ShrRa/python-intermediate-development. Would you mind raising this issue there as well?

**Comment by rachel3834** [comment]
Moving this issue to the repo of lesson materials
